#!/bin/bash

# mimicking oozie/spark running shell scripts in jenkins pipelines and getting back the logs and exit code
  jenkins='java -jar ../downloads/jenkins-cli.jar -s http://jenkins:8080/'
  SUCCESS="${1:-"true"}"

  ${jenkins} build log-test -v -f -p SUCCESS="${SUCCESS}"
