version: '2'

services:

   # Cerebro Elasticsearch client
  cerebro:
    build:
      context: cerebro/

    ports:
      - "9000:9000"
    networks:
      - elk
    depends_on:
      - elasticsearch


  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  jenkins:
    build:
      context: jenkins/
    volumes:
      - ./jenkins/jobs:/var/jenkins_home/jobs
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - logstash

networks:

  elk:
    driver: bridge
